# Generated by Django 5.1.5 on 2025-03-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
